### ISSUE TITLE
Component: specify bucket name

### ISSUE THREAD

**Issue by josephluck** [danielcondemarin/serverless-next.js#145]
Hey!

Great work with the serverless components version of the plugin, it's quite frankly excellent 👏 

What would be even better is if there was an input option for `bucketName` or something similar to avoid having the serverless framework generate a random S3 bucket name. Of course this is an optional nice-to-have, but it's would be useful to know when looking at the S3 dashboard.

**Comment by ClementChaumel** [comment]
Would it also be possible to add an option for `region`?
I tried both `serverless --region eu-west-1` 
and 
``` yml
MyApp:
  component: serverless-next.js
  inputs:
    region: eu-west-1
 ``` 

to no avail.
Thanks! and agreed, great work with the component!
