### ISSUE TITLE
Number or resources > 200

### ISSUE THREAD

**Issue by romainquellec** [danielcondemarin/serverless-next.js#17]
Finally deploying my project en AWS, I've got this : 
```
The CloudFormation template is invalid: Template format error: Number of resources, 226, is greater than maximum allowed, 200
```

I dont know this error. FWI, I've got 37 pages.

**Comment by romainquellec** [comment]
I'm looking at serverless-nested-stack, but it seems incompatible with serverless-nextjs-plugin

**Comment by romainquellec** [comment]
```
plugins:
  - serverless-nextjs-plugin
  - serverless-plugin-split-stacks

frameworkVersion: ">=1.21.0 <2.0.0"

custom:
  splitStacks:
    perFunction: true
    perType: false
```
Seems right. Dont know if we are supposed to do that

**Comment by romainquellec** [comment]
Trying some options with serverless-plugin-split-stacks, but the lambdas are not deployed.
Maybe, I'm using the plugins wrong.

**Comment by romainquellec** [comment]
FYI, I think this is the most important issue right now, as 30 is not a big number for pages.

**Comment by danielcondemarin** [comment]
@romainquellec It's definitely on my radar. 
Seems like it **might** be addressed in the serverless framework itself: https://github.com/serverless/serverless/issues/3411

If you don't need function versioning you can switch it off:
```yml
# serverless.yml
provider:
  versionFunctions: false
```
That's 37 *less* resources. 

Also, I will look into why `serverless-plugin-split-stacks` or nested-stacks doesn't work with the plugin.
