### ISSUE TITLE
Redirect non-www to www and vice-versa

### ISSUE THREAD

**Issue by amursky** [danielcondemarin/serverless-next.js#192]
Add an option to enable redirect from `example.com` to `www.example.com` and vice-versa.
For example, add option `redirect` to force redirect to www:

```
myApp:
  component: serverless-next.js
  inputs:
    domain: ["www", "example.com"]
    redirect: true
```
