### ISSUE TITLE
YAML config variables

### ISSUE THREAD

**Issue by mbenitezm** [danielcondemarin/serverless-next.js#199]
Hi!

I'm migrating a project that used the old plugin to this component but I'm having some issues with the serverless.yml file.

Previously I used this to assign the bucketName:
```
custom:
  serverless-nextjs:
    assetsBucketName: ${file(./s3BucketName.js):s3BucketName}
```

and now it looks like this:
```
appName:
  component: serverless-next.js
  inputs:
    bucketName: ${file(./s3BucketName.js):s3BucketName}
```

`${file(./s3BucketName.js):s3BucketName}` doesn't seem to be working any longer as I get the error: ` InvalidBucket: Bucket names cannot contain forward slashes. Bucket: ${file(./s3BucketName.js):s3BucketName}`

After this I went through serverless components Readme and it said I could use env variables in the yaml, so I changed the bucketName assignment to: `bucketName: ${env.BUCKET_NAME}` and now get error: `Error: invalid reference ${env.BUCKET_NAME}`

The reason behind trying to do it this way is because I have multiple environments on which I want to deploy. So depending on the environment variable I set the name of the s3BucketName, but now I find no way to read this or the environment variable.

Also. I was able before to set the stage this way, but I no longer know where this config should be written, or if it should be written at all: 
```
provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 512
  stage: ${opt:stage, 'dev'}
```

I'm not sure if I'm missing something, as I can't find any docs or examples, or if this is an actual bug with variables.

Thanks!!

**Comment by barrysteyn** [comment]
Using serverless components is very different to using the old serverless plugins. For one thing, you cannot mix the "old" style with the "new" style. So instance, you cannot use a provider.

**Comment by jepperip** [comment]
I am having a similar problem.
I want to create custom domains for different stages with the help of variables, like this:
```yml
nextApp:
  component: "serverless-next.js"
  inputs:
    domain:
      - ${opt:stage, 'dev'}
      - "mydomain.com"
```
This creates template-files where the domain is resolved to `"domain": "${opt:stage, 'dev'}.mydomain.com`, which is not want I want.
