### ISSUE TITLE
Error on AWS: ApiGatewayResourceProxyVar resource already has a variable path part

### ISSUE THREAD

**Issue by gustavorps** [danielcondemarin/serverless-next.js#206]
**Describe the bug**
```
Serverless: Operation failed!
Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A420353426084%3Astack%2Ffbhunter-applications-web-survey-dev%2F35d163b0-eebf-11e9-9861-0a325fb8c980
 
  Serverless Error ---------------------------------------
 
  An error occurred: ApiGatewayResourceProxyVar - A sibling ({uid}) of this resource already has a variable path part -- only one is allowed (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: 011205b8-7ed0-445a-8743-4d0b55d79264).
```

**To Reproduce**
1. Create a react-next-app
2. Follow this `serverless`
```
service: app-web-survey
stage: dev
region: sa-east-1

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128

plugins:
  - serverless-nextjs-plugin

package:
  exclude:
    - ./**
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

```
Operating System:          linux
Node Version:              10.15.1
Framework Version:         1.54.0
Plugin Version:            3.1.2
SDK Version:               2.1.2
Components Core Version:   1.1.1
Components CLI Version:    1.2.3
```
