### ISSUE TITLE
Add the possibility to read output from other components

### ISSUE THREAD

**Issue by murar8** [danielcondemarin/serverless-next.js#218]
**Is your feature request related to a problem? Please describe.**
First of all thanks for writing this component but right now I have the following problem: I don't see any way for next to read the output of another plugin. I know Lambda@Edge does not support enviroment variables bo we should consider to at least pass the enviroment variables to next so they can be hardcoded during build.

**Describe the solution you'd like**
Add a buildEnv input that can set enviroment variables so they can be read by the next builder.

For example in serverless.yml:
```yaml
application:
  component: "serverless-next.js"
  inputs:
    buildEnv:
      userPoolId: ${cognito.UserPoolId}

cognito:
  component: "@serverless/aws-cloudformation"
  inputs:
    stackName: cognito
    disableRollback: true
    template: ./cognito.yml
````

And then in next.config.js:
```js
module.exports = {
  target: "serverless",
  env: {
    userPoolId: process.env.userPoolId
  }
};
```

I don't know if there is a simpler way to do this but this seems like a viable option.
