### ISSUE TITLE
.serverless folder get changed every deploy

### ISSUE THREAD

**Issue by billzhong** [danielcondemarin/serverless-next.js#225]
**Describe the bug**
The `.serverless` folder has a few `Template.json` files to save important information like S3 bucket name and cloudfront ID. So I commit the folder to git repo. However, the folder files get changed every time I run `npx serverless` deploy command. More specific, the hash in `defaultEdgebda.json` and `origin-request` in `CloudFront.json` get changed.

**To Reproduce**
1. run `npx serverless`
2. check git local changes
3. run `npx serverless`
4. check git local changes

**Expected behavior**
Files should not get changed every deployment.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.15.1

**Additional context**
I would like to use `github actions` to deploy every push. What is the best practice?

**Comment by nodabladam** [comment]
I use CircleCI do deploy every push and also need to know how to handle this so I can do CI/CD releases without having to commit back to the repo despite there being no changes:

![image](https://user-images.githubusercontent.com/57159187/68156080-e85c7600-feff-11e9-8ade-608df3c20364.png)

@danielcondemarin Do you know if we actually need to commit the changes beyond the initial ones assuming that no bucket or domain settings have changed?

**Comment by danielcondemarin** [comment]
> More specific, the hash in defaultEdgebda.json and origin-request in CloudFront.json get changed

This happens because a new version of the Lambda@Edge functions is published on every deploy. 

> @danielcondemarin Do you know if we actually need to commit the changes beyond the initial ones assuming that no bucket or domain settings have changed?

I don't think you need to. On every deploy a new version of the lambda is published anyway so whatever version is currently published is overridden.

I'm going to close this issue assuming there are no side effects of not committing these particular state changes referred in the issue. Feel free to re-open if you find any functional issues as a result of this.

**Comment by diegopamio** [comment]
> **Additional context**
> I would like to use `github actions` to deploy every push. What is the best practice?

@billzhong were you able to use `github actions` ? and so how? I've tried using standard serverless action but as I expected it didn't work (doesn't find next binary)

**Comment by billzhong** [comment]
> > **Additional context**
> > I would like to use `github actions` to deploy every push. What is the best practice?
> 
> @billzhong were you able to use `github actions` ? and so how? I've tried using standard serverless action but as I expected it didn't work (doesn't find next binary)

Yes. I use GitHub actions and it works for me. If it doesn't work for you, what is the `log`?

**Comment by diegopamio** [comment]
This is my `main.yml`:

```yml
on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm install
      uses: actions/setup-node@v1
      with:
        node-version: '12.14.0'
        args: install
    - name: serverless deploy
      uses: serverless/github-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

And this is what I get:
```
9s › myNextApplication › Error: Command failed with exit code 2 (ENOENT): node_modules/.bin/next build
```

it's like the deploy can't find the next binary after npm install (btw, next it is included in `package.json`). I'm using next 9.1

**Comment by billzhong** [comment]
@diegopamio try `npx serverless deploy`

**Comment by diegopamio** [comment]
@billzhong if you meant:

```yml
on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm install
      uses: actions/setup-node@v1
      with:
        node-version: '12.14.0'
        args: install
    - name: serverless deploy
      run: npx serverless deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

Then I got `Error: "component" input is required to run custom methods. `

**Comment by diegopamio** [comment]
I've now tried with just `npx serverless` (as per Serverless-next doc) and I've got the same `next binary not found` issue.

**Comment by billzhong** [comment]
Here is my yaml deploy section:
```yaml
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npx next build
    - run: npx serverless
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```
I hope this helps.
