### ISSUE TITLE
Ability to configure all cloudfront inputs

### ISSUE THREAD

**Issue by barrysteyn** [danielcondemarin/serverless-next.js#270]
One of the features that I always need to update is the ability to configure cloudfront. Rather than making one off input configurations for each feature (e.g. forwarding certain headers), can I suggest rather allowing one to configure any cloudfront options that are available from [@serverless/aws-cloudfront](https://github.com/serverless-components/aws-cloudfront), like so:

```
myNextApplication:
  component: serverless-next.js
  inputs:
     cloudfront:
        default:
            inputs here
        api:
            inputs here
```

The idea is that anything you have not set could be set by these inputs. For example, I need user-agent forwarding and I want to whitelist what cloudfront allows me to do regarding headers.

This would solve #240 #198 It would also make other future requests asking for cloudfront changes obsolete.

What do you think? I can get a PR for this out quite quickly.
