### ISSUE TITLE
Setting timeout with serverless.yml doesn't work

### ISSUE THREAD

**Issue by JerryGreen** [danielcondemarin/serverless-next.js#273]
**Describe the bug**

The `timeout` setting in my `serverless.yml` doesn't work. Deployed functions have their default 10 seconds.

> For me this is especially important for `pages/api` functions, not just `pages`

**Steps to reproduce**

Deploy a project with one of the following configs:

```yml
# serverless.yml
my-app:
  component: serverless-next.js
  inputs:
    timeout: 90
    memory: 1024
```

```yml
# serverless.yml
my-app:
  component: serverless-next.js
  inputs:
    timeout:
      apiLambda: 90
    memory:
      apiLambda: 1024
```

**Expected behavior**
My `timeout` setting to be equal 1 minute 30 seconds.

**Screenshots**
Btw, `memory` input works, but `timeout` doesn't:

<img width="628" alt="image" src="https://user-images.githubusercontent.com/13215662/71610538-c6a40600-2bb3-11ea-866e-c135dc82e424.png">

**Desktop:**
 - OS: macOS
 - Version: 10.15.2

**Serverless versions:**
Framework Core: 1.60.4
Plugin: 3.2.6
SDK: 2.2.1
Components Core: 1.1.2
Components CLI: 1.4.0

"serverless-next.js": "1.7.3"

**Additional context**
I'm trying to mitigate 503 error, which seems to be pretty popular:

https://github.com/danielcondemarin/serverless-next.js/issues/181
https://github.com/danielcondemarin/serverless-next.js/issues/222
https://github.com/danielcondemarin/serverless-next.js/issues/146

My `pages/api` function is pretty time consuming, will take about a minute (I'm playing with puppeteer and [chrome-aws-lambda](https://github.com/alixaxel/chrome-aws-lambda))
