### ISSUE TITLE
Log groups not created for Lambda functions

### ISSUE THREAD

**Issue by mdw2000** [danielcondemarin/serverless-next.js#312]
I'm trying to debug an issue on a page that has a `getServerSideProps` handler, but after deploying the application I cannot find the log group for my lambda function in any of the regions.

The application uses `next@9.3.0` with `getServerSideProps`.

My understanding is that after deployment there should be automatically be a `/aws/lambda/us-east-1.<function-name>` log group in every region, correct?

My `serverless.yml` config:
```
ssr:
  component: serverless-next.js
  inputs:
    domain:
      - ${env.subdomain}
      - xxxxxxx
    memory: 2048
    timeout:
      defaultLambda: 20
      apiLambda: 15
    bucketName: xxxxxxxx
    policy: ${env.policy}
```

`serverless.js`:
```
class Deploy extends Component {
  async default(inputs = {}) {
    process.env.policy = getConfig().ssrPolicyArn;
    process.env.subdomain = `subdomain-${process.env.ENV}`;

    const template = await this.load('@serverless/template', process.env.ENV);
    const output = await template({ template: 'serverless.yml' });
    return output;

  }
...
...
```

My custom policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "dynamodb:Query",
            "Resource": "arn:aws:dynamodb:eu-west-1:xxxxxx:table/wwwwwww"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogStream",
                "logs:CreateLogGroup",
                "logs:PutLogEvents"
            ],
            "Resource": "*"
        }
    ]
}
```
