### ISSUE TITLE
want to change _next/* and static/* ttl

### ISSUE THREAD

**Issue by watanabeyu** [danielcondemarin/serverless-next.js#375]
I want to change `static/*` ttl, so that I use SSG with Next9.3.0
Also I know rfc, but it's difficult soon.

I want to be able change like below.

```yml
inputs:
  cloudfront:
    origins:
      - url:...
        pathPatterns:
          "static/*":
            ttl:0
```

https://github.com/danielcondemarin/serverless-next.js/blob/1c2c0dc9a5f2b2d0c8a3c68e561c4539822aa9f9/packages/serverless-component/serverless.js#L156-L169
```js
    const cloudFrontOrigins = [
      {
        url: bucketUrl,
        private: true,
        pathPatterns: {
          "_next/*": {
            ttl: _nexTTL
          },
          "static/*": {
            ttl: staticTTL
          }
        }
      }
    ];
```

**Comment by stan-sack** [comment]
Ive got a PR for this: https://github.com/danielcondemarin/serverless-next.js/pull/282. If you really need the feature you can pull the branch.

**Comment by danielcondemarin** [comment]
The PR @stan-sack is now merged and published. Please see https://github.com/danielcondemarin/serverless-next.js/blob/master/README.md#custom-cloudfront-configuration for more info.

**Comment by teemuniiranen** [comment]
I didn't understand from the documentation how to do this. I tried with:
```
customerFrontendNextApp:
    component: "serverless-next.js@1.9.5"
    inputs:
      nextConfigDir: "../../"
      bucketName: my-hostingbucket-develop
      cloudfront:
        origins:
          - url: /static
            pathPatterns:
              static/*:
                ttl: 600
```
