### ISSUE TITLE
All builds are suddenly failing due to recent changes

### ISSUE THREAD

**Issue by SarKurd** [danielcondemarin/serverless-next.js#396]
All our building are failing because of the recent changes to lambda-at-edge package.

How do we lock the version? i have locked the version of serverless-next.js in my package.json but it doesn't work.

```sh
using sls version 
  error:
  /root/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.0/node_modules/@sls-next/lambda-at-edge/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.0/node_modules/@sls-next/lambda-at-edge/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
```

**the state file**
```json
{
  "components": {
    "myapp": "/root/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.0/node_modules/serverless-next.js"
  }
}
```

Most recent version i tested that was working was `1.9.8`, i need to be able to lock it to that version

**Comment by SarKurd** [comment]
Silly me, you can do it in the yml file. but still there is a bug with the new versions.

**Comment by marianogappa** [comment]
@SarKurd could you share some context on this? We might be experiencing the same problem, and we haven't fixed it yet.

**Comment by danielcondemarin** [comment]
Hi folks, I'll be looking at why this happens tonight. In the meantime you can pin the version of serverless-next.js:

```
# serverless.yml
component: serverless-next.js@{version_here}
...

**Comment by SavageWilliam** [comment]
Our production cloudfront distribution broke due to queryStrings suddenly not being forwarded. I believe it were the changes here

https://github.com/danielcondemarin/serverless-next.js/commit/e7bed6aa8d0a8f7fd332e1d0c37d8dc67ec3aa65#diff-04c6e90faac2675aa89e2176d2eec7d8R128

package json:
` "serverless-next.js": "^1.9.10",` 

Our serverless.yml was:

```

myNextApplication:
  component: serverless-next.js
  inputs:
    domain: [**hidden**]
    cloudfront:
      defaults: # options for lambda that handle SSR
        forward:
          headers: [CloudFront-Is-Mobile-Viewer]
  build:
    env:
      NODE_ENV: production
```

Updated to:


```

myNextApplication:
  component: serverless-next.js
  inputs:
    domain: [**hidden**]
    cloudfront:
      defaults: # options for lambda that handle SSR
        forward:
          headers: [CloudFront-Is-Mobile-Viewer]
          cookies: "all"
          queryString: true
  build:
    env:
      NODE_ENV: production
```

in order to fix

**Comment by SarKurd** [comment]
@marianogappa that's what i did, for now i stick with 1.9.8, i know it's working.

> Hi folks, I'll be looking at why this happens tonight. In the meantime you can pin the version of serverless-next.js:
> 
> ```
> # serverless.yml
> component: serverless-next.js@{version_here}
> ...
> ```

**Comment by danielcondemarin** [comment]
@SarKurd Do you mind sharing your `serverless.yml`? I wasn't able to replicate this issue.

**Comment by SarKurd** [comment]
Here the config for both Serverless.yml and serverless.js files, it's a liitle messy but works for us :)

```yml
name: portal

myappPortal:
  component: serverless-next.js@1.9.8
  inputs:
    domain:
      - ${env.subdomain}
      - ${env.domain}
    bucketName: ${env.bucketName}

```

serveless.js

```js
const fs = require('fs');

const yaml = require('js-yaml');
const aws = require('aws-sdk');
const { Component } = require('@serverless/core');

function addPolicy(policy) {
    const doc = yaml.safeLoad(fs.readFileSync('./serverless.yml', 'utf8'));
    doc.myappPortal.inputs = {
        ...doc.myappPortal.inputs,
        policy,
    };

    return doc;
}

const { STAGE } = process.env;

class Deploy extends Component {
    async default() {
        if (STAGE === 'test' || STAGE === 'dev' || STAGE === 'staging' || STAGE === 'prod') {
            // Will load .env-${stage} as environment variables
            require('dotenv').config({ path: `${__dirname}/resources/environments/.env-${STAGE}` });

            const iam = new aws.IAM({ credentials: this.context.credentials.aws });
            const sts = new aws.STS({ credentials: this.context.credentials.aws });

            let policyArn = '';

            try {
                const identity = await sts.getCallerIdentity().promise();

                policyArn = `arn:aws:iam::${identity.Account}:policy/myAppPolicy`;

                const params = {
                    PolicyDocument: JSON.stringify({
                        Version: '2012-10-17',
                        Statement: [
                            {
                                Effect: 'Allow',
                                Action: 'secretsmanager:GetSecretValue',
                                Resource: `*`,
                            },
                            {
                                Effect: 'Allow',
                                Action: [
                                    'logs:CreateLogGroup',
                                    'logs:CreateLogStream',
                                    'logs:PutLogEvents',
                                ],
                                Resource: '*',
                            },
                        ],
                    }),
                    PolicyName: 'myAppPolicy',
                    Description: 'Policy used by my app website',
                    Path: null,
                };

                await iam
                    .createPolicy(params)
                    .promise()
                    .catch(err => {
                        if (err.code !== 'EntityAlreadyExists') {
                            throw new Error(err);
                        }
                    });
            } catch (error) {
                throw new Error(error);
            }

            const doc = addPolicy(policyArn);

            const template = await this.load('@serverless/template', STAGE);

            const output = await template({ template: doc });
            return output;
        }
        this.context.log('No environment defined... Choices are test, dev, staging or prod');
    }

    async remove() {
        this.context.log('Please manually delete the resources');
    }
}

module.exports = Deploy;

```
