### ISSUE TITLE
Every deployment using github actions or circleci makes a cloudfront and two lambdas

### ISSUE THREAD

**Issue by teajoon** [danielcondemarin/serverless-next.js#409]
I am using github actions as CI.
However, every deployment using github actions or circleci makes a cloudfront and two lambdas in different with local deployment.
Local deployment does not make lambdas and a cloudfront.

Is there anyway to block making new cloudfront and lambda?

- serverless.yml
```
test:
  component: serverless-next.js@1.11.1
  name: test-front
  org: test
  app: test-front
  inputs:
    name:
      defaultLambda: testLambda
      apiLambda: testApi
    memory:
      defaultLambda: 512
      apiLambda: 1024
    bucketName: test-front-next
```
