### ISSUE TITLE
zip file oversize, can't be uploaded to AWS

### ISSUE THREAD

**Issue by CyrilleFormont** [danielcondemarin/serverless-next.js#424]
**Describe the bug**
I'm facing a 404LambdaFunction issue due to the oversize of the zip file.
My zip file is about 70mo, unzipped it became 270mo.

The project is using typescript.

It doesn't contain any assets as they are all on S3, moreover I excluded, in the serverless.yaml, all unecessary file.

```
service: 'ProjectName-${self:provider.stage}'
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev','prod'}
  region: ap-southeast-2
plugins: 
  - serverless-nextjs-plugin
  - serverless-dotenv-plugin
custom:
  name: ProjectName-${self:provider.stage}
  serverless-nextjs: 
    assetsBucketName: 'ProjectName-${self:provider.stage}'
package:
  exclude:
    - ./**

```

Each page is about 13mo and looks like the following:
- home.js 1ko
- home.original.js 13mo
- index.js 1ko
- index.original.js 13mo

![image](https://user-images.githubusercontent.com/22873760/83472691-3b64ce80-a4cb-11ea-9fc4-706bbd4e8c3d.png)

 - Version "serverless-nextjs-plugin": "^2.5.0-alpha.0",

I might forget something ? 
I tried to : 
- publish with "individually : true"
- add :  useServerlessTraceTarget: true

Thank you!
