### ISSUE TITLE
Throttling: Rate exceeded when deploying in CI/CD

### ISSUE THREAD

**Issue by fean** [danielcondemarin/serverless-next.js#441]
**Describe the bug**
We have a simple Next.js app. It has two pages and no API  lambda's at this moment. Deploying it locally works like a charm.

When we moved it to our Gitlab CI pipeline. It started throwing the following error consistently:
```
Throttling: Rate exceeded
     at Request.extractError (/root/.serverless/components/registry/npm/serverless-next.js@1.13.0/node_modules/aws-sdk/lib/protocol/query.js:50:29)
     at Request.callListeners (/root/.serverless/components/registry/npm/serverless-next.js@1.13.0/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
     at Request.emit (/root/.serverless/components/registry/npm/serverless-next.js@1.13.0/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
     at Request.emit (/root/.serverless/components/registry/npm/serverless-next.js@1.13.0/node_modules/aws-sdk/lib/request.js:683:14)
     at Request.transition (/root/.serverless/components/registry/npm/serverless-next.js@1.13.0/node_modules/aws-sdk/lib/request.js:22:10)
     at AcceptorStateMachine.runTo (/root/.serverless/components/registry/npm/serverless-next.js@1.13.0/node_modules/aws-sdk/lib/state_machine.js:14:12)
     at /root/.serverless/components/registry/npm/serverless-next.js@1.13.0/node_modules/aws-sdk/lib/state_machine.js:26:10
     at Request.<anonymous> (/root/.serverless/components/registry/npm/serverless-next.js@1.13.0/node_modules/aws-sdk/lib/request.js:38:9)
     at Request.<anonymous> (/root/.serverless/components/registry/npm/serverless-next.js@1.13.0/node_modules/aws-sdk/lib/request.js:685:12)
     at Request.callListeners (/root/.serverless/components/registry/npm/serverless-next.js@1.13.0/node_modules/aws-sdk/lib/sequential_executor.js:116:18) 

{
   code: 'Throttling',
   time: 2020-06-12T10:21:05.448Z,
   requestId: 'dfdacc4e-9a19-4b7a-90cb-2930d565e773',
   statusCode: 400,
   retryable: true
 }
```

This is a masked representation of our serverless.yml file:
```yml
appStaging:
  component: serverless-next.js@1.13.0
  inputs:
    domain: [sub, domain.ext]
    name:
      defaultLambda: lambda-name-dev
      apiLambda: api-lambda-name-dev
    bucketName: bucket-name-dev
    memory:
      defaultLambda: 512
      apiLambda: 1024
```

The CI runner uses the `node:12-alpine` docker image to run the deployment.

**To Reproduce**
1. Create a simple app
2. Do a deployment in Gitlab CI through `npx serverless`

**Expected behavior**
We expect the pipeline to deploy our application as it was locally.

**Desktop (please complete the following information):**
 - OS: Alpine Linux
 - Version: 3.11
