### ISSUE TITLE
Question: How to use with serverless.com ci/cd

### ISSUE THREAD

**Issue by mjtodd** [danielcondemarin/serverless-next.js#450]
I'm trying to work out how this should be setup with a ci/cd pipeline. 

Do those pipelines support components, and if so, how would parameters defined in the deployment profile for my different stages get passed through as next.js build time environment variables?

For my backend projects I would just pass through as param references e.g.  ${param:API_URL}, so I was hoping that could be passed through in build.env but it doesn't seem like this would be supported?

**Comment by dan-turner** [comment]
Yes would be interested to know this too.  Even just how to integrate with the serverless.com dashboard.

Simply running `serverless` does indeed seem to deploy the app, but it doesn't appear in my serverless.com dashboard despite having specified an org and app:

```
service:
  name: tex-app
  # app and org for use with dashboard.serverless.com
app: tex-app
org: texinc

myApp:
  component: serverless-next.js
```
