### ISSUE TITLE
pages-manifest not found. Check if `next.config.js` target is set to 'serverless'

### ISSUE THREAD

**Issue by teajoon** [danielcondemarin/serverless-next.js#467]
I know it is closed via other issue. #447 
However, in my case, i am still watching the error while deploying.
My serverless.yml file is like this.
```
inputs:
    name:
      defaultLambda: popupcinemaLambda
      apiLambda: popupcinemaApi
    memory:
      defaultLambda: 512
      apiLambda: 1024
    bucketName: popupcinema-front-next
    build:
      args: ['build', '--max-old-space-size=8192']
    cloudfront: 
      api/*:
        forward:
          headers:
            [
              Authorization,
              Content-Type
            ]
```

I think "--max-old-space-size=8192" makes this error.
But I have to put the build option since there is an javascript heap size error while deploying.
If I remove "args: ['build', '--max-old-space-size=8192']", pages-manifest error is not occured.
But it is stopped with javascript heap size error.

I am using the lastest version(1.14.0 or 1.15.0-alpha.0)

Thanks for making this good library.

**Comment by lone-cloud** [comment]
How long does your build take before failing with that error? It's highly unusual to be running out of heap space in the first place, so I'm trying to understand what makes your app different. How many pages are in your app?

What happens if you add the `useServerlessTraceTarget: true` input?

**Comment by teajoon** [comment]
It is about 80 pages.
I am migrating from angular+SSR to nextjs+SSR.

```
What happens if you add the useServerlessTraceTarget: true input?
```
I put the code, but the error is still going on.. 
If u need to see my project, i can send u an invitation.

**Comment by lone-cloud** [comment]
You'll have to read the README yourself and conduct your own debugging.
The pages-manifest is created only for serverless-type builds. You should ensure that `next build` runs correctly for your project and that the manifest file is generated in the .next directory. The serverless-nextjs build runs it in the same way. An upcoming PR #466 adds a new "verbose" input that will may offer some insight on this failure.

**Comment by danielcondemarin** [comment]
@teajoon Any luck with this? Have you tried using the latest version of the project? `@sls-next/serverless-component@1.15.1`

**Comment by mithunsen-int** [comment]
I'm facing the same issue. 
```sh 
pages-manifest not found. Check if `next.config.js` target is set to 'serverless'
```

Here is my configuration. 
```JSON
"next": "^9.5.5",
```
```yml
myapp:
    component: "@sls-next/serverless-component@1.18.0"
    inputs:
        name: ${env.BUILD_INSTANCE}
        memory: 512
        bucketName: ${env.BUILD_INSTANCE}
        useServerlessTraceTarget: true
```

**Comment by krish-dev** [comment]
@danielcondemarin I'm also facing the same issue. 
```sh 
pages-manifest not found. Check if `next.config.js` target is set to 'serverless'
```

Here is my configuration. 
```JSON
"next": "^9.5.5",
```
```yml
myapp:
    component: "@sls-next/serverless-component@1.18.0"
    inputs:
        name: ${env.BUILD_INSTANCE}
        memory: 512
        bucketName: ${env.BUILD_INSTANCE}
        useServerlessTraceTarget: true
```
